export const ACCUMULATORS = [
  {
    name: 'BOSH S3 016',
    naimenovanie: 'Аккумулятор',
    img: '../../../assets/img/details/accumulator/bosch_s3.jpg',
    price: 191,
    voltage: '12B',
    capacity: '45 А/ч',
  },
  {
    name: 'BOSH S4 006',
    naimenovanie: 'Аккумулятор',
    img: '../../../assets/img/details/accumulator/bosch-s4.jpg',
    price: 222,
    voltage: '12B',
    capacity: '60 А/ч',
  },
  {
    name: 'BOSH S5 004',
    naimenovanie: 'Аккумулятор',
    img: '../../../assets/img/details/accumulator/bosch-s5.jpg',
    price: 289,
    voltage: '12B',
    capacity: '61 А/ч',
  },
  {
    name: 'EDCON DC35300R',
    naimenovanie: 'Аккумулятор',
    img: '../../../assets/img/details/accumulator/edcon-35-a-ch.jpg',
    price: 143,
    voltage: '12B',
    capacity: '35 А/ч',
  },
  {
    name: 'EDCON DC56480R',
    naimenovanie: 'Аккумулятор',
    img: '../../../assets/img/details/accumulator/edcon-56-a-ch.jpg',
    price: 160,
    voltage: '12B',
    capacity: '56 А/ч',
  },
  {
    name: 'EDCON DC91740R',
    naimenovanie: 'Аккумулятор',
    img: '../../../assets/img/details/accumulator/edcon-91-a-ch.jpg',
    price: 200,
    voltage: '12B',
    capacity: '91 А/ч',
  },
  {
    name: 'EXIDE EXCELL EB712',
    naimenovanie: 'Аккумулятор',
    img: '../../../assets/img/details/accumulator/Exide_EB712.jpg',
    price: 280,
    voltage: '12B',
    capacity: '71 А/ч',
  },
  {
    name: 'EXIDE PPREMIIM EA722',
    naimenovanie: 'Аккумулятор',
    img: '../../../assets/img/details/accumulator/Exide_EA722.jpg',
    price: 285,
    voltage: '12B',
    capacity: '72 А/ч',
  },
  {
    name: 'EXIDE START-STOP EFB EL652',
    naimenovanie: 'Аккумулятор',
    img: '../../../assets/img/details/accumulator/Exide_EL652.jpg',
    price: 307,
    voltage: '12B',
    capacity: '65 А/ч',
  },
  {
    name: 'VARTA BLUE DYNAMIC B31',
    naimenovanie: 'Аккумулятор',
    img: '../../../assets/img/details/accumulator/varta-blue-dynamic-b31.jpg',
    price: 180,
    voltage: '12B',
    capacity: '45 А/ч',
  },
  {
    name: 'VARTA BLUE DYNAMIC F17',
    naimenovanie: 'Аккумулятор',
    img: '../../../assets/img/details/accumulator/varta-blue-dynamic-f17-80ach.jpg',
    price: 351,
    voltage: '12B',
    capacity: '80 А/ч',
  },
  {
    name: 'VARTA SILVER DYNAMIC D15',
    naimenovanie: 'Аккумулятор',
    img: '../../../assets/img/details/accumulator/varta-silver-dynamic-d15.jpg',
    price: 279,
    voltage: '12B',
    capacity: '63 А/ч',
  },
  {
    name: 'VARTA BLUE DYNAMIC A15',
    naimenovanie: 'Аккумулятор',
    img: '../../../assets/img/details/accumulator/varta_blue_dynamic_a15.jpg',
    price: 203,
    voltage: '12B',
    capacity: '40 А/ч',
  },
  {
    name: 'VARTA BLUE DYNAMIC B18',
    naimenovanie: 'Аккумулятор',
    img: '../../../assets/img/details/accumulator/varta_blue_dynamic_b18.jpg',
    price: 222,
    voltage: '12B',
    capacity: '44 А/ч',
  },
];
