export const AIR_FILTERS = [
  {
    name: 'HENGST FILTER E488L',
    naimenovanie: 'Воздушный фильтр',
    img: '../../../assets/img/details/air-filters/HENGST_E488L.jpg',
    price: 26.29,
    height: 70,
    long: 344,
  },
  {
    name: 'BLUE PRINT ADB112225',
    naimenovanie: 'Воздушный фильтр',
    img: '../../../assets/img/details/air-filters/BLUEPRINT_ADB11.jpg',
    price: 67.47,
    height: 77,
    long: 366,
  },
  {
    name: 'BLUE PRINT ADG022113',
    naimenovanie: 'Воздушный фильтр',
    img: '../../../assets/img/details/air-filters/BLUEPRINT_ADG022.jpg',
    price: 22.89,
    height: 54,
    long: 258,
  },
  {
    name: 'MAHLE LX 4138',
    naimenovanie: 'Воздушный фильтр',
    img: '../../../assets/img/details/air-filters/MAXLE_LX41.jpg',
    price: 62,
    height: 36,
    long: 253,
  },
  {
    name: 'MANN-FILTER C 3463',
    naimenovanie: 'Воздушный фильтр',
    img: '../../../assets/img/details/air-filters/MANN_C3463.jpg',
    price: 16,
    height: 38,
    long: 334,
  },
  {
    name: 'ASHIKA 20-02-251',
    naimenovanie: 'Воздушный фильтр',
    img: '../../../assets/img/details/air-filters/ASHIKA_2002.jpg',
    price: 11.07,
    height: 52,
    long: 310,
  },
  {
    name: 'MAHLE LX 4431',
    naimenovanie: 'Воздушный фильтр',
    img: '../../../assets/img/details/air-filters/MAXLE_LX4431.jpg',
    price: 26.35,
    height: 51,
    long: 258,
  },
  {
    name: 'KNECHT LX 1840',
    naimenovanie: 'Воздушный фильтр',
    img: '../../../assets/img/details/air-filters/KNECHT_LX1840.jpg',
    price: 24.49,
    height: 34,
    long: 241,
  },
  {
    name: 'KNECHT LX 591',
    naimenovanie: 'Воздушный фильтр',
    img: '../../../assets/img/details/air-filters/KNECHT_LX591.jpg',
    price: 47.19,
    height: 49,
    long: 233,
  },
];
