export const FILTERS_SALONA = [
  {
    name: 'MANN-FILTER CU 24 009',
    naimenovanie: 'Салонный фильтр',
    img: '../../../assets/img/details/filters-salona/MANNFILTER_CU24009.jpg',
    price: 33,
    long: 203,
    height: 28,
    width: 214,
  },
  {
    name: 'PURFLUX AH116',
    naimenovanie: 'Салонный фильтр',
    img: '../../../assets/img/details/filters-salona/PURFLUX_AH116.jpg',
    price: 24.47,
    long: 292,
    width: 183,
    height: 19,
  },
  {
    name: 'PURFLUX AH405',
    naimenovanie: 'Салонный фильтр',
    img: '../../../assets/img/details/filters-salona/PURFLUX_AH405.jpg',
    price: 26.23,
    long: 217,
    height: 35,
    width: 200,
  },
  {
    name: 'HENGST FILTER E2998LC',
    naimenovanie: 'Салонный фильтр',
    img: '../../../assets/img/details/filters-salona/HENGST_E2998LC.jpg',
    price: 41.41,
    long: 250,
    height: 30,
    width: 235,
  },
  {
    name: 'ASHIKA 21-NS-NS20',
    naimenovanie: 'Салонный фильтр',
    img: '../../../assets/img/details/filters-salona/ASHIKA_21NS.jpg',
    price: 10.2,
    long: 228,
    height: 32,
    width: 200,
  },
  {
    name: 'MAHLE LAK 54',
    naimenovanie: 'Салонный фильтр',
    img: '../../../assets/img/details/filters-salona/MAHLELAK_54.jpg',
    price: 108.8,
    long: 273,
    height: 43,
    width: 242,
  },
  {
    name: 'BLUE PRINT ADH22515',
    naimenovanie: 'Салонный фильтр',
    img: '../../../assets/img/details/filters-salona/BLUEPRINT_ADH22515.jpg',
    price: 21.43,
    long: 211,
    height: 29,
    width: 205,
  },
  {
    name: 'BLUE PRINT ADN12506',
    naimenovanie: 'Салонный фильтр',
    img: '../../../assets/img/details/filters-salona/BLUEPRINT_ADN12506.jpg',
    price: 12.87,
    long: 224,
    height: 43,
    width: 191,
  },
  {
    name: 'FILTRON K 1428A-2x',
    naimenovanie: 'Салонный фильтр',
    img: '../../../assets/img/details/filters-salona/FILTRON_K1428A.jpg',
    price: 93.47,
    long: 229,
    height: 30,
    width: 165,
  },
];
