export const FILTERS_KOROBKI = [
  {
    name: 'KNECHT HX 153D',
    naimenovanie: 'Фильтр автоматической коробки передач',
    img: '../../../assets/img/details/filters-korobki/KNECHT_HX_153D.jpg',
    price: 73.95,
    typeakpp: 'CVT-автоматическая коробка передач (без ступеней)',
    long: 203,
  },
  {
    name: 'KNECHT HX 159KIT',
    naimenovanie: 'Фильтр автоматической коробки передач',
    img: '../../../assets/img/details/filters-korobki/KNECHT_HX_159KIT.jpg',
    price: 103.35,
    typeakpp: 'Автоматическая коробка передач 5-ступенчатая',
    long: 289,
  },
  {
    name: 'FEBI BILSTEIN 09463',
    naimenovanie: 'Фильтр автоматической коробки передач',
    img: '../../../assets/img/details/filters-korobki/FEBI_09463.jpg',
    price: 28.8,
    typeakpp: 'для автоматической коробки передач',
    long: 193,
  },
  {
    name: 'FEBI BILSTEIN 100660',
    naimenovanie: 'Фильтр автоматической коробки передач',
    img: '../../../assets/img/details/filters-korobki/FEBI_100660.jpg',
    price: 38.06,
    typeakpp: 'для автоматической коробки передач',
    long: 177,
  },
  {
    name: 'FEBI BILSTEIN 14264',
    naimenovanie: 'Фильтр автоматической коробки передач',
    img: '../../../assets/img/details/filters-korobki/FEBI_14264.jpg',
    price: 42,
    typeakpp: 'для автоматической коробки передач',
    long: 160,
  },
  {
    name: 'FEBI BILSTEIN 44176',
    naimenovanie: 'Фильтр автоматической коробки передач',
    img: '../../../assets/img/details/filters-korobki/FEBI_44176.jpg',
    price: 38.06,
    typeakpp: 'для автоматической коробки передач',
    long: 105.4,
  },
  {
    name: 'HENGST FILTER H10W22',
    naimenovanie: 'Маслянный фильтр',
    img: '../../../assets/img/details/filters-korobki/HENGST_H10W22.jpg',
    price: 20.26,
    typeakpp: 'для механической коробки передач',
    long: 185,
  },
  {
    name: 'MEYLE 014 027 2014',
    naimenovanie: 'Фильтр автоматической коробки передач',
    img: '../../../assets/img/details/filters-korobki/MEYLE_014027.jpg',
    price: 45.64,
    typeakpp: 'Автоматическая коробка передач 4-ступенчатая',
    long: 223,
  },
  {
    name: 'KNECHT HX 169KIT',
    naimenovanie: 'Фильтр автоматической коробки передач',
    img: '../../../assets/img/details/filters-korobki/KNECHT_HX169KIT.jpg',
    price: 85.03,
    typeakpp: 'Автоматическая коробка передач 6-ступенчатая',
    long: 168,
  },
];
