export const KOLODKI = [
  {
    name: 'NK 223625',
    naimenovanie: 'Тормозные колодки',
    img: '../../../assets/img/details/kolodki/NK_2236.jpg',
    price: 29.83,
    height: 42.8,
  },
  {
    name: 'NK 229986',
    naimenovanie: 'Тормозные колодки',
    img: '../../../assets/img/details/kolodki/NK_2299.jpg',
    price: 33.12,
    height: 68.5,
  },
  {
    name: 'TEXTAR 2074701',
    naimenovanie: 'Тормозные колодки',
    img: '../../../assets/img/details/kolodki/TEXTAR_2074701.jpg',
    price: 83.5,
    height: 54.6,
    tolschina: 19.9,
  },
  {
    name: 'TRW GDB3548',
    naimenovanie: 'Тормозные колодки',
    img: '../../../assets/img/details/kolodki/TRW_GDB3548.jpg',
    price: 83,
    tolschina: 17.8,
  },
  {
    name: 'ASHIKA 50-00-013',
    naimenovanie: 'Тормозные колодки',
    img: '../../../assets/img/details/kolodki/ASHIKA_50.jpg',
    price: 31.52,
    tolschina: 16.2,
  },
  {
    name: 'BLUE PRINT ADN142114',
    naimenovanie: 'Тормозные колодки',
    img: '../../../assets/img/details/kolodki/BLUEPRINT_ADN142.jpg',
    price: 44.6,
    long: 123,
  },
  {
    name: 'BLUE PRINT ADV184206',
    naimenovanie: 'Тормозные колодки',
    img: '../../../assets/img/details/kolodki/BLUEPRINT_ADV184.jpg',
    price: 40,
    long: 87,
  },
  {
    name: 'TRW MCB828SV',
    naimenovanie: 'Тормозные колодки',
    img: '../../../assets/img/details/kolodki/TRW_MCB82.jpg',
    price: 85,
    tolschina: 9,
  },
  {
    name: 'FEBI BILSTEIN 16055',
    naimenovanie: 'Тормозные колодки',
    img: '../../../assets/img/details/kolodki/FEBI_16055.jpg',
    price: 35.52,
    long: 141.4,
  },
];
