export const KOMPLECT_GRM = [
  {
    name: 'DAYCO KTB399',
    naimenovanie: 'Комплект ремня ГРМ',
    img: '../../../assets/img/details/complect-grm/DAYCO_KTB399.jpg',
    price: 493,
  },
  {
    name: 'DAYCO KTB460',
    naimenovanie: 'Комплект ремня ГРМ',
    img: '../../../assets/img/details/complect-grm/DAYCO_KTB460.jpg',
    price: 252.39,
  },
  {
    name: 'DAYCO KTB461',
    naimenovanie: 'Комплект ремня ГРМ',
    img: '../../../assets/img/details/complect-grm/DAYCO_KTB461.jpg',
    price: 169.04,
  },
  {
    name: 'SKF VKMA 01001',
    naimenovanie: 'Комплект ремня ГРМ',
    img: '../../../assets/img/details/complect-grm/SKF_T0091.jpg',
    price: 205.75,
    numberofteeth: 124,
  },
  {
    name: 'SKF VKMA 03246',
    naimenovanie: 'Комплект ремня ГРМ',
    img: '../../../assets/img/details/complect-grm/SKF_T0167.jpg',
    price: 153,
    numberofteeth: 141,
  },
  {
    name: 'SKF VKMA 05156',
    naimenovanie: 'Комплект ремня ГРМ',
    img: '../../../assets/img/details/complect-grm/SKF_T0139.jpg',
    price: 322,
    numberofteeth: 162,
  },
  {
    name: 'SNR KD452.08',
    naimenovanie: 'Комплект ремня ГРМ',
    img: '../../../assets/img/details/complect-grm/SNR_KD452.08.jpg',
    price: 289.68,
    numberofteeth: 131,
    width: 25,
  },
  {
    name: 'SNR KD453.02',
    naimenovanie: 'Комплект ремня ГРМ',
    img: '../../../assets/img/details/complect-grm/SNR_KD453.02.jpg',
    price: 101,
    numberofteeth: 111,
    width: 17,
  },
  {
    name: 'SNR KD455.43',
    naimenovanie: 'Комплект ремня ГРМ',
    img: '../../../assets/img/details/complect-grm/SNR_KD455.43.jpg',
    price: 353,
    numberofteeth: 128,
    width: 27,
  },
  {
    name: 'INA 530 0171 10',
    naimenovanie: 'Комплект ремня ГРМ',
    img: '../../../assets/img/details/complect-grm/INA_530017110.jpg',
    price: 143,
    numberofteeth: 138,
    width: 23,
  },
  {
    name: 'INA 530 0582 10',
    naimenovanie: 'Комплект ремня ГРМ',
    img: '../../../assets/img/details/complect-grm/INA_530058210.jpg',
    price: 225,
    numberofteeth: 132,
    width: 28,
  },
];
