export const MASL_FILTERS = [
  {
    name: 'PURFLUX LS867B',
    naimenovanie: 'Масляный фильтр',
    img: '../../../assets/img/details/masl-filters/PURFLUX_LS867B.jpg',
    price: 14.77,
    height: 85,
    diameter: 76,
  },
  {
    name: 'MAHLE OC 195',
    naimenovanie: 'Масляный фильтр',
    img: '../../../assets/img/details/masl-filters/MAHLE_OC195.jpg',
    price: 10.66,
    height: 65.6,
    diameter: 54.5,
  },
  {
    name: 'MAHLE OC 196',
    naimenovanie: 'Масляный фильтр',
    img: '../../../assets/img/details/masl-filters/MAHLE_OC196.jpg',
    price: 11.24,
    height: 85.6,
    diameter: 65,
  },
  {
    name: 'MAHLE OC 264',
    naimenovanie: 'Масляный фильтр',
    img: '../../../assets/img/details/masl-filters/MAHLE_OC264.jpg',
    price: 17.75,
    height: 120.5,
    diameter: 76,
  },
  {
    name: 'MAHLE OC 295',
    naimenovanie: 'Масляный фильтр',
    img: '../../../assets/img/details/masl-filters/MAHLE_OC295.jpg',
    price: 14.72,
    height: 91.5,
    diameter: 78,
  },
  {
    name: 'MAHLE OC 47 OF',
    naimenovanie: 'Масляный фильтр',
    img: '../../../assets/img/details/masl-filters/MAHLE_OC47.jpg',
    price: 12.4,
    height: 120,
    diameter: 76,
  },
  {
    name: 'KOLBENSCHMIDT 50014678',
    naimenovanie: 'Масляный фильтр',
    img: '../../../assets/img/details/masl-filters/KOLBENSCHMIDT.jpg',
    price: 12.14,
    height: 79,
    diameter: 65,
  },
  {
    name: 'PURFLUX LS932',
    naimenovanie: 'Масляный фильтр',
    img: '../../../assets/img/details/masl-filters/PURFLUX_LS932.jpg',
    price: 12.95,
    height: 54,
    diameter: 76,
  },
  {
    name: 'HENGST FILTER E11H D57',
    naimenovanie: 'Масляный фильтр',
    img: '../../../assets/img/details/masl-filters/HENGST_FILTER.jpg',
    price: 21.52,
    height: 117,
    diameter: 65,
  },
];
