export const REMEN_GRM = [
  {
    name: 'GATES 5244XS',
    naimenovanie: 'Зубчатый ремень ГРМ',
    img: '../../../assets/img/details/remen-grm/GATES_5244XS.jpg',
    price: 23.86,
    numberofteeth: 124,
    width: 25,
    long: 141,
  },
  {
    name: 'GATES 5265XS',
    naimenovanie: 'Зубчатый ремень ГРМ',
    img: '../../../assets/img/details/remen-grm/GATES_5265XS.jpg',
    price: 27.8,
    numberofteeth: 145,
    width: 21,
    long: 116,
  },
  {
    name: 'GATES 5521',
    naimenovanie: 'Зубчатый ремень ГРМ',
    img: '../../../assets/img/details/remen-grm/GATES_5521.jpg',
    price: 25.26,
    numberofteeth: 111,
    width: 19,
    long: 105,
  },
  {
    name: 'DAYCO 941060',
    naimenovanie: 'Зубчатый ремень ГРМ',
    img: '../../../assets/img/details/remen-grm/DAYCO_94167.jpg',
    price: 51.93,
    numberofteeth: 163,
    width: 20,
  },
  {
    name: 'DAYCO 94167',
    naimenovanie: 'Зубчатый ремень ГРМ',
    img: '../../../assets/img/details/remen-grm/DAYCO_941060.jpg',
    price: 35.55,
    numberofteeth: 163,
    width: 26.7,
  },
  {
    name: 'DAYCO 94224',
    naimenovanie: 'Зубчатый ремень ГРМ',
    img: '../../../assets/img/details/remen-grm/DAYCO_941060.jpg',
    price: 37.69,
    numberofteeth: 136,
    width: 26.7,
  },
  {
    name: 'DAYCO 94300',
    naimenovanie: 'Зубчатый ремень ГРМ',
    img: '../../../assets/img/details/remen-grm/DAYCO_94167.jpg',
    price: 28.78,
    numberofteeth: 111,
    width: 21,
  },
  {
    name: 'DAYCO 94303',
    naimenovanie: 'Зубчатый ремень ГРМ',
    img: '../../../assets/img/details/remen-grm/DAYCO_94167.jpg',
    price: 20.26,
    numberofteeth: 128,
    width: 19,
  },
  {
    name: 'DAYCO 94664',
    naimenovanie: 'Зубчатый ремень ГРМ',
    img: '../../../assets/img/details/remen-grm/DAYCO_941060.jpg',
    price: 64.65,
    numberofteeth: 154,
    width: 30,
  },
];
