export const TOPL_FILTERS = [
  {
    name: 'PURFLUX C491',
    naimenovanie: 'Топливный фильтр',
    img: '../../../assets/img/details/topl-filters/PURFLUX_C491.jpg',
    price: 22.37,
    height: 120,
    diameter: 71,
  },
  {
    name: 'PURFLUX C493E',
    naimenovanie: 'Топливный фильтр',
    img: '../../../assets/img/details/topl-filters/PURFLUX_C493E.jpg',
    price: 19.02,
    height: 93,
    diameter: 71,
  },
  {
    name: 'HENGST FILTER H140WK',
    naimenovanie: 'Топливный фильтр',
    img: '../../../assets/img/details/topl-filters/HENGSTFILTER_H140WK.jpg',
    price: 39.41,
    height: 127,
    diameter: 92,
  },
  {
    name: 'MEAT & DORIA 4111',
    naimenovanie: 'Топливный фильтр',
    img: '../../../assets/img/details/topl-filters/MEATDORIA_4111.jpg',
    price: 27.14,
    height: 177,
    diameter: 86,
  },
  {
    name: 'MEAT & DORIA 4245',
    naimenovanie: 'Топливный фильтр',
    img: '../../../assets/img/details/topl-filters/MEATDORIA_4245.jpg',
    price: 41.41,
    height: 165,
    diameter: 87,
  },
  {
    name: 'HENGST FILTER H154WK',
    naimenovanie: 'Топливный фильтр',
    img: '../../../assets/img/details/topl-filters/HENGSTFILTER_H154WK.jpg',
    price: 54.06,
    height: 163,
    diameter: 71,
  },
  {
    name: 'MEAT & DORIA 4113',
    naimenovanie: 'Топливный фильтр',
    img: '../../../assets/img/details/topl-filters/MEATDORIA_4113.jpg',
    price: 25.1,
    height: 180,
    diameter: 86,
  },
  {
    name: 'BLUE PRINT ADZ92310',
    naimenovanie: 'Топливный фильтр',
    img: '../../../assets/img/details/topl-filters/BLUEPRINT_ADZ92310.jpg',
    price: 11.69,
    height: 93,
    diameter: 20,
  },
  {
    name: 'BOSCH F 026 402 533',
    naimenovanie: 'Топливный фильтр',
    img: '../../../assets/img/details/topl-filters/BOSCH_F026.jpg',
    price: 54.44,
    height: 77,
    diameter: 65.4,
  },
];
