export const TORMOZ_DISKI = [
  {
    name: 'BOSCH 0 986 478 867',
    naimenovanie: 'Тормозной диск',
    img: '../../../assets/img/details/tormoz-diski/BOSH_0986.jpg',
    price: 149,
    height: 34.5,
    type: 'вентилируемый',
    tolschina: 25,
  },
  {
    name: 'BREMBO 08.C172.10',
    naimenovanie: 'Тормозной диск',
    img: '../../../assets/img/details/tormoz-diski/BREMBO_08.C172.jpg',
    price: 80.33,
    height: 44,
    type: 'полный',
    tolschina: 10,
  },
  {
    name: 'A.B.S. 17889',
    naimenovanie: 'Тормозной диск',
    img: '../../../assets/img/details/tormoz-diski/ABS_17889.jpg',
    price: 83.5,
    type: 'с внутренней вентиляцией',
    height: 44,
  },
  {
    name: 'BLUE PRINT ADG043132',
    naimenovanie: 'Тормозной диск',
    img: '../../../assets/img/details/tormoz-diski/BLUEPRINT_ADG043132.jpg',
    price: 66.83,
    type: 'вентилируемый',
    tolschina: 61,
  },
  {
    name: 'BLUE PRINT ADG043136',
    naimenovanie: 'Тормозной диск',
    img: '../../../assets/img/details/tormoz-diski/BLUEPRINT_ADG043136.jpg',
    price: 108.11,
    type: 'вентилируемый',
    tolschina: 47,
  },
  {
    name: 'BLUE PRINT ADP154301',
    naimenovanie: 'Тормозной диск',
    img: '../../../assets/img/details/tormoz-diski/BLUEPRINT_ADP154301.jpg',
    price: 106.35,
    type: 'вентилируемый',
    tolschina: 34,
  },
  {
    name: 'FEBI BILSTEIN 14160',
    naimenovanie: 'Тормозной диск',
    img: '../../../assets/img/details/tormoz-diski/FEBI_14160.jpg',
    price: 127.3,
    type: 'с внешней вентиляцией',
    tolschina: 55.4,
  },
  {
    name: 'FEBI BILSTEIN 17212',
    naimenovanie: 'Тормозной диск',
    img: '../../../assets/img/details/tormoz-diski/FEBI_17212.jpg',
    price: 54.62,
    type: 'вентилируемый',
    tolschina: 42,
  },
  {
    name: 'SWAG 60 90 9071',
    naimenovanie: 'Тормозной диск',
    img: '../../../assets/img/details/tormoz-diski/SWAG_6090.jpg',
    price: 47.7,
    type: 'вентилируемый',
    tolschina: 55.4,
  },
];
