export const SUPPORTS = [
  {
    name: 'NK 2145175',
    naimenovanie: 'Тормозной суппорт',
    img: '../../../assets/img/details/supports/NK_2145175.jpg',
    price: 146.66,
    type: 'суппорт тормоза (1 поршень)',
    material: 'Чугун',
  },
  {
    name: 'TRW BHN165',
    naimenovanie: 'Тормозной суппорт',
    img: '../../../assets/img/details/supports/TRW_BHN165.jpg',
    price: 313.05,
    type: 'автоматическая регулировка',
    material: 'Чугун',
  },
  {
    name: 'TRW BHN275',
    naimenovanie: 'Тормозной суппорт',
    img: '../../../assets/img/details/supports/TRW_BHN275.jpg',
    price: 175.64,
    type: `Тормозной суппорт со встр. стояночной системой`,
    material: 'Алюминий',
  },
  {
    name: 'JP GROUP 1162000970',
    naimenovanie: 'Тормозной суппорт',
    img: '../../../assets/img/details/supports/JPGROUP_1162000970.jpg',
    price: 159.14,
    type: 'Тормозной суппорт со встр. стояночной системой',
    material: 'Алюминий',
  },
  {
    name: 'TRW BHN354',
    naimenovanie: 'Тормозной суппорт',
    img: '../../../assets/img/details/supports/TRW_BHN354.jpg',
    price: 180.31,
    type: 'Тормозной суппорт со встр. стояночной системой',
    material: 'Чугун',
  },
  {
    name: 'BOSCH 0 986 134 000',
    naimenovanie: 'Тормозной суппорт',
    img: '../../../assets/img/details/supports/BOSCH_0986.jpg',
    price: 551.44,
    type: 'Тормозной суппорт со встр. стояночной системой',
    material: 'Алюминий',
  },
  {
    name: 'NK 2119144',
    naimenovanie: 'Тормозной суппорт',
    img: '../../../assets/img/details/supports/NK_2119144.jpg',
    price: 166.44,
    type: 'суппорт тормоза (2 поршня)',
    material: 'Алюминий',
  },
  {
    name: 'FTE RX529823A0',
    naimenovanie: 'Тормозной суппорт',
    img: '../../../assets/img/details/supports/FTE_RX529.jpg',
    price: 180.75,
    type: 'суппорт с плавающей скобой (2 поршня)',
    material: 'Чугун',
  },
  {
    name: 'FTE RX529824A0',
    naimenovanie: 'Тормозной суппорт',
    img: '../../../assets/img/details/supports/FTE_RX529824A0.jpg',
    price: 93.47,
    type: 'суппорт с плавающей скобой (2 поршня)',
    material: 'Чугун',
  },
];
